// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR8x34sstEcRsGlSkaOzh0mSgxwsvi5u4',
    appId: '1:236591396684:web:3f45c856096be83911c1e9',
    messagingSenderId: '236591396684',
    projectId: 'authtutorial-f8220',
    authDomain: 'authtutorial-f8220.firebaseapp.com',
    storageBucket: 'authtutorial-f8220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqBx533iZz-awCpSR1Ggh7rMCQmEi2oM',
    appId: '1:236591396684:android:911bfec9f58a6ef811c1e9',
    messagingSenderId: '236591396684',
    projectId: 'authtutorial-f8220',
    storageBucket: 'authtutorial-f8220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw2i1Fv_NR61pNESZQd2P2HKfhrEsBU_0',
    appId: '1:236591396684:ios:75120733eaefc30811c1e9',
    messagingSenderId: '236591396684',
    projectId: 'authtutorial-f8220',
    storageBucket: 'authtutorial-f8220.appspot.com',
    iosClientId: '236591396684-j43kr9rc6kph0asj0vp35029dsj8pnv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw2i1Fv_NR61pNESZQd2P2HKfhrEsBU_0',
    appId: '1:236591396684:ios:00c5b290ca8daf8f11c1e9',
    messagingSenderId: '236591396684',
    projectId: 'authtutorial-f8220',
    storageBucket: 'authtutorial-f8220.appspot.com',
    iosClientId: '236591396684-jf5fagkjbafcg01tsfp7khbh67infp0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLoginPage.RunnerTests',
  );
}
